# Generated by Django 5.2.12 on 2026-03-23 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alternative_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='alternative_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_registration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_contacted',
        ),
        migrations.RemoveField(
            model_name='client',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='other_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='preferred_communication',
        ),
        migrations.RemoveField(
            model_name='client',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='client',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='client',
            name='working_hours',
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('other', 'Other')], default='office', max_length=20)),
                ('address_line1', models.CharField(blank=True, default='', max_length=300)),
                ('address_line2', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(blank=True, default='', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.client')),
            ],
            options={
                'verbose_name_plural': 'client addresses',
                'ordering': ['-is_primary', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('registration', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.client')),
            ],
            options={
                'verbose_name_plural': 'client companies',
                'ordering': ['-is_current', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('mobile', 'Mobile'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('skype', 'Skype'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=300)),
                ('label', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('other', 'Other')], default='work', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client')),
            ],
            options={
                'ordering': ['-is_primary', 'contact_type'],
            },
        ),
    ]
