# Generated by Django 5.2.12 on 2026-03-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_normalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Job Tracker', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('footer_text', models.CharField(blank=True, default='', max_length=300)),
                ('show_footer', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('accent_color', models.CharField(default='#6c757d', max_length=7)),
                ('sidebar_bg_light', models.CharField(default='#212529', max_length=7)),
                ('sidebar_text_light', models.CharField(default='#adb5bd', max_length=7)),
                ('topbar_bg_light', models.CharField(default='#212529', max_length=7)),
                ('sidebar_bg_dark', models.CharField(default='#1a1d21', max_length=7)),
                ('sidebar_text_dark', models.CharField(default='#adb5bd', max_length=7)),
                ('topbar_bg_dark', models.CharField(default='#1a1d21', max_length=7)),
                ('login_bg_color', models.CharField(default='#212529', max_length=7)),
                ('login_bg_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('default_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
