# Generated by Django 5.2.12 on 2026-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_app_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='primary_color',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='accent_color_dark',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='accent_color_light',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='primary_color_dark',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='primary_color_light',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
    ]
