# Generated by Django 5.2.12 on 2026-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_smtp_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=models.TextField(blank=True, default=''),
        ),
    ]
