# Generated by Django 5.2.12 on 2026-05-17 16:56

import django.db.models.deletion
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('core', 'ExpenseCategory')
    defaults = ['Connects', 'Marketing', 'Office', 'Other', 'Software', 'Subscription', 'Tools']
    for name in defaults:
        ExpenseCategory.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_encrypt_smtp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.expensecategory'),
        ),
    ]
